//
// AnimationPartaCarView.swift
// Generated by Core Animator version 1.3.1 on 25/02/2016.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

import UIKit

protocol AnimationPartaCarViewDelegate: class {
	func buttonInscriPressed(buttonInscri: UIButton)
	func buttonCo2Pressed(buttonCo2: UIButton)
}

@IBDesignable
class AnimationPartaCarView : UIView {


	var animationCompletions = Dictionary<CAAnimation, (Bool) -> Void>()
	var viewsByName: [String : UIView]!

	// - MARK: Life Cycle

	convenience init() {
		self.init(frame: CGRect(x: 0, y: 0, width: 1080, height: 1920))
	}

	override init(frame: CGRect) {
		super.init(frame: frame)
		self.setupHierarchy()
	}

	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		self.setupHierarchy()
	}

	weak var animationPartaCarViewDelegate: AnimationPartaCarViewDelegate?

	// - MARK: Scaling

	override func layoutSubviews() {
		super.layoutSubviews()

		if let scalingView = self.viewsByName["__scaling__"] {
			var xScale = self.bounds.size.width / scalingView.bounds.size.width
			var yScale = self.bounds.size.height / scalingView.bounds.size.height
			switch contentMode {
			case .ScaleToFill:
				break
			case .ScaleAspectFill:
				let scale = max(xScale, yScale)
				xScale = scale
				yScale = scale
			default:
				let scale = min(xScale, yScale)
				xScale = scale
				yScale = scale
			}
			scalingView.transform = CGAffineTransformMakeScale(xScale, yScale)
			scalingView.center = CGPoint(x:CGRectGetMidX(self.bounds), y:CGRectGetMidY(self.bounds))
		}
	}

	// - MARK: Setup

	func setupHierarchy() {
		var viewsByName: [String : UIView] = [:]
		let bundle = NSBundle(forClass:self.dynamicType)
		let __scaling__ = UIView()
		__scaling__.bounds = CGRect(x:0, y:0, width:1080, height:1920)
		__scaling__.center = CGPoint(x:540.0, y:960.0)
		self.addSubview(__scaling__)
		viewsByName["__scaling__"] = __scaling__

		let logolaunch = UIImageView()
		logolaunch.bounds = CGRect(x:0, y:0, width:347.0, height:347.0)
		logolaunch.layer.anchorPoint = CGPoint(x:0.506, y:0.508)
		var imgLogolaunch: UIImage!
		if let imagePath = bundle.pathForResource("logolaunch.png", ofType:nil) {
			imgLogolaunch = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from 'logolaunch.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		logolaunch.image = imgLogolaunch
		logolaunch.contentMode = .Center
		logolaunch.layer.position = CGPoint(x:542.728, y:383.289)
		logolaunch.transform = CGAffineTransformMakeScale(1.35, 1.36)
		__scaling__.addSubview(logolaunch)
		viewsByName["logolaunch"] = logolaunch

		let buttonInscri = UIButton(type: .Custom)
		buttonInscri.bounds = CGRect(x:0, y:0, width:450.0, height:200.0)
		var imgButtonInscri: UIImage!
		if let imagePath = bundle.pathForResource("buttonInscri.png", ofType:nil) {
			imgButtonInscri = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from 'buttonInscri.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		buttonInscri.setBackgroundImage(imgButtonInscri, forState:.Normal)
		buttonInscri.contentMode = .Center
		buttonInscri.layer.position = CGPoint(x:540.000, y:1359.483)
		buttonInscri.transform = CGAffineTransformMakeScale(0.86, 0.82)
		buttonInscri.addTarget(self, action:"actionButtonInscriPressed:", forControlEvents: .TouchUpInside)
		__scaling__.addSubview(buttonInscri)
		viewsByName["buttonInscri"] = buttonInscri

		let buttonCo2 = UIButton(type: .Custom)
		buttonCo2.bounds = CGRect(x:0, y:0, width:625.0, height:277.0)
		var imgButtonCo2: UIImage!
		if let imagePath = bundle.pathForResource("buttonCo2.png", ofType:nil) {
			imgButtonCo2 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from 'buttonCo2.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		buttonCo2.setBackgroundImage(imgButtonCo2, forState:.Normal)
		buttonCo2.contentMode = .Center
		buttonCo2.layer.position = CGPoint(x:540.000, y:1196.327)
		buttonCo2.transform = CGAffineTransformMakeScale(0.65, 0.62)
		buttonCo2.addTarget(self, action:"actionButtonCo2Pressed:", forControlEvents: .TouchUpInside)
		__scaling__.addSubview(buttonCo2)
		viewsByName["buttonCo2"] = buttonCo2

		self.viewsByName = viewsByName
	}

	// - MARK: mouvement

	func addMouvementAnimation() {
		addMouvementAnimationWithBeginTime(0, fillMode: kCAFillModeBoth, removedOnCompletion: false, completion: nil)
	}

	func addMouvementAnimation(completion: ((Bool) -> Void)?) {
		addMouvementAnimationWithBeginTime(0, fillMode: kCAFillModeBoth, removedOnCompletion: false, completion: completion)
	}

	func addMouvementAnimation(removedOnCompletion removedOnCompletion: Bool) {
		addMouvementAnimationWithBeginTime(0, fillMode: removedOnCompletion ? kCAFillModeRemoved : kCAFillModeBoth, removedOnCompletion: removedOnCompletion, completion: nil)
	}

	func addMouvementAnimation(removedOnCompletion removedOnCompletion: Bool, completion: ((Bool) -> Void)?) {
		addMouvementAnimationWithBeginTime(0, fillMode: removedOnCompletion ? kCAFillModeRemoved : kCAFillModeBoth, removedOnCompletion: removedOnCompletion, completion: completion)
	}

	func addMouvementAnimationWithBeginTime(beginTime: CFTimeInterval, fillMode: String, removedOnCompletion: Bool, completion: ((Bool) -> Void)?) {
		let linearTiming = CAMediaTimingFunction(name: kCAMediaTimingFunctionLinear)
		if let complete = completion {
			let representativeAnimation = CABasicAnimation(keyPath: "not.a.real.key")
			representativeAnimation.duration = 0.670
			representativeAnimation.delegate = self
			self.layer.addAnimation(representativeAnimation, forKey: "Mouvement")
			self.animationCompletions[layer.animationForKey("Mouvement")!] = complete
		}

		let logolaunchOpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		logolaunchOpacityAnimation.duration = 0.670
		logolaunchOpacityAnimation.values = [0.000 as Float, 1.000 as Float, 1.000 as Float]
		logolaunchOpacityAnimation.keyTimes = [0.000 as Float, 0.746 as Float, 1.000 as Float]
		logolaunchOpacityAnimation.timingFunctions = [linearTiming, linearTiming]
		logolaunchOpacityAnimation.beginTime = beginTime
		logolaunchOpacityAnimation.fillMode = fillMode
		logolaunchOpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["logolaunch"]?.layer.addAnimation(logolaunchOpacityAnimation, forKey:"mouvement_Opacity")

		let logolaunchTranslationXAnimation = CAKeyframeAnimation(keyPath: "transform.translation.x")
		logolaunchTranslationXAnimation.duration = 0.670
		logolaunchTranslationXAnimation.values = [-700.000 as Float, 50.000 as Float, 0.000 as Float, 30.000 as Float]
		logolaunchTranslationXAnimation.keyTimes = [0.000 as Float, 0.746 as Float, 0.881 as Float, 1.000 as Float]
		logolaunchTranslationXAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		logolaunchTranslationXAnimation.beginTime = beginTime
		logolaunchTranslationXAnimation.fillMode = fillMode
		logolaunchTranslationXAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["logolaunch"]?.layer.addAnimation(logolaunchTranslationXAnimation, forKey:"mouvement_TranslationX")

		let logolaunchTranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		logolaunchTranslationYAnimation.duration = 0.670
		logolaunchTranslationYAnimation.values = [0.000 as Float, 0.000 as Float, 0.000 as Float]
		logolaunchTranslationYAnimation.keyTimes = [0.000 as Float, 0.791 as Float, 1.000 as Float]
		logolaunchTranslationYAnimation.timingFunctions = [linearTiming, linearTiming]
		logolaunchTranslationYAnimation.beginTime = beginTime
		logolaunchTranslationYAnimation.fillMode = fillMode
		logolaunchTranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["logolaunch"]?.layer.addAnimation(logolaunchTranslationYAnimation, forKey:"mouvement_TranslationY")

		let buttonInscriOpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		buttonInscriOpacityAnimation.duration = 0.670
		buttonInscriOpacityAnimation.values = [0.000 as Float, 1.000 as Float, 1.000 as Float]
		buttonInscriOpacityAnimation.keyTimes = [0.000 as Float, 0.746 as Float, 1.000 as Float]
		buttonInscriOpacityAnimation.timingFunctions = [linearTiming, linearTiming]
		buttonInscriOpacityAnimation.beginTime = beginTime
		buttonInscriOpacityAnimation.fillMode = fillMode
		buttonInscriOpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["buttonInscri"]?.layer.addAnimation(buttonInscriOpacityAnimation, forKey:"mouvement_Opacity")

		let buttonInscriTranslationXAnimation = CAKeyframeAnimation(keyPath: "transform.translation.x")
		buttonInscriTranslationXAnimation.duration = 0.670
		buttonInscriTranslationXAnimation.values = [-700.000 as Float, 0.000 as Float, 0.000 as Float]
		buttonInscriTranslationXAnimation.keyTimes = [0.000 as Float, 0.746 as Float, 1.000 as Float]
		buttonInscriTranslationXAnimation.timingFunctions = [linearTiming, linearTiming]
		buttonInscriTranslationXAnimation.beginTime = beginTime
		buttonInscriTranslationXAnimation.fillMode = fillMode
		buttonInscriTranslationXAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["buttonInscri"]?.layer.addAnimation(buttonInscriTranslationXAnimation, forKey:"mouvement_TranslationX")

		let buttonInscriTranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		buttonInscriTranslationYAnimation.duration = 0.670
		buttonInscriTranslationYAnimation.values = [0.000 as Float, 0.000 as Float]
		buttonInscriTranslationYAnimation.keyTimes = [0.000 as Float, 1.000 as Float]
		buttonInscriTranslationYAnimation.timingFunctions = [linearTiming]
		buttonInscriTranslationYAnimation.beginTime = beginTime
		buttonInscriTranslationYAnimation.fillMode = fillMode
		buttonInscriTranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["buttonInscri"]?.layer.addAnimation(buttonInscriTranslationYAnimation, forKey:"mouvement_TranslationY")

		let buttonCo2OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		buttonCo2OpacityAnimation.duration = 0.670
		buttonCo2OpacityAnimation.values = [0.000 as Float, 1.000 as Float, 1.000 as Float]
		buttonCo2OpacityAnimation.keyTimes = [0.000 as Float, 0.746 as Float, 1.000 as Float]
		buttonCo2OpacityAnimation.timingFunctions = [linearTiming, linearTiming]
		buttonCo2OpacityAnimation.beginTime = beginTime
		buttonCo2OpacityAnimation.fillMode = fillMode
		buttonCo2OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["buttonCo2"]?.layer.addAnimation(buttonCo2OpacityAnimation, forKey:"mouvement_Opacity")

		let buttonCo2TranslationXAnimation = CAKeyframeAnimation(keyPath: "transform.translation.x")
		buttonCo2TranslationXAnimation.duration = 0.670
		buttonCo2TranslationXAnimation.values = [-700.000 as Float, 0.000 as Float, 0.000 as Float]
		buttonCo2TranslationXAnimation.keyTimes = [0.000 as Float, 0.746 as Float, 1.000 as Float]
		buttonCo2TranslationXAnimation.timingFunctions = [linearTiming, linearTiming]
		buttonCo2TranslationXAnimation.beginTime = beginTime
		buttonCo2TranslationXAnimation.fillMode = fillMode
		buttonCo2TranslationXAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["buttonCo2"]?.layer.addAnimation(buttonCo2TranslationXAnimation, forKey:"mouvement_TranslationX")
	}

	func removeMouvementAnimation() {
		self.layer.removeAnimationForKey("Mouvement")
		self.viewsByName["logolaunch"]?.layer.removeAnimationForKey("mouvement_Opacity")
		self.viewsByName["logolaunch"]?.layer.removeAnimationForKey("mouvement_TranslationX")
		self.viewsByName["logolaunch"]?.layer.removeAnimationForKey("mouvement_TranslationY")
		self.viewsByName["buttonInscri"]?.layer.removeAnimationForKey("mouvement_Opacity")
		self.viewsByName["buttonInscri"]?.layer.removeAnimationForKey("mouvement_TranslationX")
		self.viewsByName["buttonInscri"]?.layer.removeAnimationForKey("mouvement_TranslationY")
		self.viewsByName["buttonCo2"]?.layer.removeAnimationForKey("mouvement_Opacity")
		self.viewsByName["buttonCo2"]?.layer.removeAnimationForKey("mouvement_TranslationX")
	}

	override func animationDidStop(anim: CAAnimation, finished flag: Bool) {
		if let completion = self.animationCompletions[anim] {
			self.animationCompletions.removeValueForKey(anim)
			completion(flag)
		}
	}

	func removeAllAnimations() {
		for subview in viewsByName.values {
			subview.layer.removeAllAnimations()
		}
		self.layer.removeAnimationForKey("Mouvement")
	}

	func actionButtonInscriPressed(buttonInscri: UIButton) {
		animationPartaCarViewDelegate?.buttonInscriPressed(buttonInscri)
	}

	func actionButtonCo2Pressed(buttonCo2: UIButton) {
		animationPartaCarViewDelegate?.buttonCo2Pressed(buttonCo2)
	}
}